apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local 10.96.0.0/12 {
           pods insecure
           upstream 8.8.8.8 8.8.4.4
        }
        prometheus :9153
        proxy . 8.8.8.8 8.8.4.4
        cache 30
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system

